FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Download NLTK data
RUN python -c "import nltk; nltk.download('punkt')"

COPY . .

# Expose port for Streamlit
EXPOSE 8054

ENV API_URL=http://nlp-prediction-api:8000

CMD ["streamlit", "run", "app/app.py", "--server.port", "8054", "--server.address", "0.0.0.0"]
