global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # In docker-compose, service names are DNS names
  - job_name: nlp-prediction-api
    static_configs:
      - targets: ["nlp-prediction-api:8000"]
    metrics_path: /metrics

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
